name: web_gnom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  flutter_mobx: ^2.2.1+1
  supabase_flutter: ^2.7.0
  app_links: ^3.2.0
  objectbox: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/empty.png
    - assets/images/gnom1.jpeg
    - assets/images/gnom2.jpeg


  fonts:
    - family: Nekst
      fonts:
        - asset: assets/fonts/Nekst-Regular.ttf