name: web_gnom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  flutter_mobx: ^2.2.1+1
  supabase_flutter: ^2.7.0
  app_links: ^3.2.0
  email_sender: ^1.4.2
  image_picker: ^1.1.2
  file_picker: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatars/empty.png
    - assets/images/avatars/avatar0.JPG
    - assets/images/avatars/avatar1.JPG
    - assets/images/gnoms/gnom1.jpeg
    - assets/images/gnoms/gnom2.jpeg
    - assets/images/gnoms/gnom3.jpeg
    - assets/images/gnoms/gnom4.jpeg
    - assets/images/gnoms/gnom5.jpeg
    - assets/images/gnoms/gnom6.jpeg
    - assets/images/gnoms/gnom7.jpeg
    - assets/images/gnoms/gnom8.jpeg
    - assets/images/gnoms/gnom9.jpeg
    - assets/images/gnoms/gnom10.png
    - assets/images/gnoms/gnom11.png

  fonts:
    - family: Nekst
      fonts:
        - asset: assets/fonts/Nekst-Regular.ttf